/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cancellation.java
 *
 * Created on 13-Feb-2011, 21:53:20
 */

package TicketBooking;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author Piravin Satkunarajah
 */
public class Cancellation extends javax.swing.JFrame {

    /** Creates new form Cancellation */
    public Cancellation() {
        initComponents();
    }

    //Retrieves the booking record from the BOOKINGS table using the booking
    //number and then updates the record by changing the CANCELLED field to
    //'Y'
     public void enterBookingNum()
    {
     String bookingNumString = txtBookingNum.getText();

     if(bookingNumString.equals(""))
     {
         lblMessage.setText("Booking number needs be entered");
     }
     else
     {
         try{
            int bookingNum = Integer.parseInt(bookingNumString);

            //connect to the database
            DatabaseConnect.init();
            Connection conn = DatabaseConnect.getConnection();

            //enable SQL statements to be created and run
            Statement stmt= conn.createStatement();

            //create and execute query
            String query = "SELECT * FROM BOOKINGS WHERE BOOKING_ID = "+ bookingNum + " AND CANCELLED = 'N' ";
            ResultSet result = stmt.executeQuery(query);

            //get the time for the first film of the day
            if (result != null && result.next())
            {
              lblMessage.setText("Booking Cancelled");
              stmt.execute("UPDATE BOOKINGS SET CANCELLED = 'Y' WHERE BOOKING_ID = "+ bookingNum +" ");
              stmt.execute("UPDATE BOOKINGS SET PRINTED = 'N' WHERE BOOKING_ID = "+ bookingNum +"");
            }
            else
            {
              lblMessage.setText("Booking Number does not exist or already cancelled");
            }
            stmt.close();
            conn.close();
            }
            catch (Exception ex)
            {
                System.err.print("SQLException: ");
                System.err.println(ex.getMessage());
            }
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPickUpTitle = new javax.swing.JLabel();
        lblEnterBookingNum = new javax.swing.JLabel();
        txtBookingNum = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        btnPrintTickets = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        lblPickUpTitle.setFont(new java.awt.Font("Impact", 0, 24));
        lblPickUpTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPickUpTitle.setText("CANCEL BOOKINGS");

        lblEnterBookingNum.setText("Enter booking number:");

        lblMessage.setText("Message");

        btnPrintTickets.setText("Cancel Bookings");
        btnPrintTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintTicketsActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPickUpTitle)
                            .addComponent(lblEnterBookingNum)
                            .addComponent(txtBookingNum, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnPrintTickets)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPickUpTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterBookingNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBookingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnPrintTickets))
                .addGap(98, 98, 98)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintTicketsActionPerformed
      enterBookingNum();
}//GEN-LAST:event_btnPrintTicketsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPrintTickets;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnterBookingNum;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPickUpTitle;
    private javax.swing.JTextField txtBookingNum;
    // End of variables declaration//GEN-END:variables

}
