

package TicketBooking;

import java.sql.*;

/**
 *
 * @author Piravin
 */
public class LoginGUI extends javax.swing.JFrame {

    /** Creates new form LoginGUI */
    public LoginGUI() {
        initComponents();
    }

    /** Login method */
    public void tryLogin()
    {
        try{
            //connect to the database
            DatabaseConnect.init();
            Connection conn = DatabaseConnect.getConnection();

            //enable SQL statements to be created and run
            Statement stmt= conn.createStatement();

            //retrieve login fields from interface
            String user = jTxtUserName.getText();
            String pass = jTxtPassword.getText();

            //create and execute query
            ResultSet result = stmt.executeQuery("SELECT * from STAFF where USER_NAME = '"+ user +"' AND PASSWORD = '" + pass +"'");

            //check if result returned and take appropriate action
            if (result.next())
            {
                lblMessage.setText("Login Successful");
                openGUI(user, pass);
            }
            else
            {
                lblMessage.setText("Login Unsuccessful");
            }

            stmt.close();
            conn.close();
        }
        catch (Exception ex)
        {
            System.err.print("SQLException: ");
                   System.err.println(ex.getMessage());
        }
    }

    public void openGUI(String user, String pass)
    {
       try{
            //connect to the database
            DatabaseConnect.init();
            Connection conn = DatabaseConnect.getConnection();

            //enable SQL statements to be created and run
            Statement stmt= conn.createStatement();


            //create and execute query
            ResultSet result = stmt.executeQuery("SELECT OCCUPATION from STAFF where USER_NAME = '"+ user +"' AND PASSWORD = '" + pass +"' AND OCCUPATION = 'Team Leader' OR OCCUPATION = 'Manager' OR OCCUPATION = 'Adminstrator'");

            //check if result returned and take appropriate action
            if (result.next())
            {
                new TeamLeaderScreen().setVisible(true);
                this.dispose();
            }
            else
            {
                new Booking().setVisible(true);
                this.dispose();
            }

            stmt.close();
            conn.close();
        }
        catch (Exception ex)
        {
            System.err.print("SQLException: ");
                   System.err.println(ex.getMessage());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoginGUI = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblEnterUserName = new javax.swing.JLabel();
        lblEnterPassword = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        lblOdeonLogo = new javax.swing.JLabel();
        lblCreator = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setForeground(new java.awt.Color(0, 153, 204));

        jPanelLoginGUI.setBackground(new java.awt.Color(0, 153, 204));

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblWelcome.setForeground(new java.awt.Color(0, 153, 204));
        lblWelcome.setText("Welcome to CineTix System - Please Login");

        lblEnterUserName.setForeground(new java.awt.Color(0, 153, 204));
        lblEnterUserName.setText("Enter User Name");

        lblEnterPassword.setForeground(new java.awt.Color(0, 153, 204));
        lblEnterPassword.setText("Enter Password");

        jTxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserNameActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogin)
                        .addGap(20, 20, 20))
                    .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLoginLayout.createSequentialGroup()
                            .addComponent(lblEnterPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTxtPassword))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLoginLayout.createSequentialGroup()
                            .addComponent(lblEnterUserName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterUserName)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterPassword)
                    .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnLogin))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblOdeonLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_odeon.png"))); // NOI18N

        lblCreator.setText("By Piravin Satkunarajah");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginGUILayout = new javax.swing.GroupLayout(jPanelLoginGUI);
        jPanelLoginGUI.setLayout(jPanelLoginGUILayout);
        jPanelLoginGUILayout.setHorizontalGroup(
            jPanelLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginGUILayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginGUILayout.createSequentialGroup()
                .addContainerGap(432, Short.MAX_VALUE)
                .addComponent(lblCreator)
                .addContainerGap())
            .addGroup(jPanelLoginGUILayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lblOdeonLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(18, 18, 18))
        );
        jPanelLoginGUILayout.setVerticalGroup(
            jPanelLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoginGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginGUILayout.createSequentialGroup()
                        .addComponent(lblOdeonLogo)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanelLoginGUILayout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblCreator)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoginGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLoginGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    tryLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
     this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelLoginGUI;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtUserName;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblEnterPassword;
    private javax.swing.JLabel lblEnterUserName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOdeonLogo;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables

}
